### PR TITLE
Refactoring the package and add pdos schema

### PR DESCRIPTION
**Pull request by unkcpz**
The proposed format for the pdos input data and schema check for the file.
The schema for the PDOS is TBD. 

For easy review of the schema:
- The example pdos file is: https://github.com/unkcpz/widget-bandsplot/blob/add-pdos-schema/examples/data/Co_dos.json
- The schema is: https://github.com/unkcpz/widget-bandsplot/blob/add-pdos-schema/widget_bandsplot/schemas/pdos.json

pinning @yakutovicha to have a look at the scheme, whether this one conforms with the use case in your app?

### CODE REVIEW

**Comment by unkcpz** [comment]
@dou-du If possible please add me as a maintainer (not sure I can, I am also pinning @giovannipizzi since this repo is under `osscar-org`.), I have a thorough the look at the repository and refactoring the python part.

**Comment by dou-du** [comment]
> @dou-du If possible please add me as a maintainer (not sure I can, I am also pinning @giovannipizzi since this repo is under `osscar-org`.), I have a thorough the look at the repository and refactoring the python part.

Yes, I just added you as maintainer.

**Comment by unkcpz** [comment]
Thanks!

**Comment by unkcpz** [comment]
@dou-du Why you merge this one?? I still have not changed the schema. Please be very careful and make sure you have *REALLY* review the PR.

**Comment by unkcpz** [comment]
Please revert this PR thanks!

**Comment by unkcpz** [comment]
And for the commit message, need to be rebased to make it more clear. It is now a big mess! Please check https://docs.github.com/en/get-started/using-git/about-git-rebase for how to rebase.

**Pull request merged**
