### PR TITLE
Extension the band structure plot to cover the fat bands use cases

### PR DESCRIPTION
**Pull request by unkcpz**
This is the part we are going to add after the meeting with Carlo and Junfeng. The goal is to extend the widget so the fat bands (see below) can be plotted. 

image

### CODE REVIEW

**Comment by dou-du** [comment]
> _ No description provided. _

Could you give more information about this issue? Thanks!

**Comment by unkcpz** [comment]
Hi @dou-du, please don't say thanks. I'd appreciate it if next time you can make some notes by yourself and get things done in time. If you have a problem I'd always be willing to help.
If you don't want to work on some specific issue like this one, please shout out during the meeting or you can always let us know what you plan to do and how much time you devote to the things related to this widget.

**Comment by dou-du** [comment]
> I update the description, this is the discussion between we too and Carlo and Junfeng to extend the widget to be more versatile.
> 
> Hi @dou-du, please don't say thanks. I'd appreciate it if next time you can make some notes by yourself and get things done in time. If you have a problem I'd always be willing to help. If you don't want to work on some specific issue like this one, please shout out during the meeting or you can always let us know what you plan to do and how much time you devote to the things related to this widget.

Hi Jusong,

I just did not remember what this PR is for and want to know more information. I am always willing to finalize and improve the widget. Criticizing me not getting things done in time is totally unaccepted. Please be clear that I am fully employed by OSSCAR project and OSSCAR project is always my top priority. Besides, I have already tried my best and spend a lot time to imporve this widget.

For this widget, there are some important tasks needed to done, for instance upgrading for ipywidget 8.x and using chart.js 0.3.x. I have already spent a lot time on these tasks. I am willing to work with you cooperatively and finlizing the widget before the end of contract. 

Finally, I still want to thank you for being frankly and helping me to improve this widget.

Dou

**Comment by eimrek** [comment]
Converted to issue: #57

**Pull request closed without merging**
