### PR TITLE
Transparency for DOS data

### LINKED ISSUE #19: Add transparency control to the background of (P)DOS lines

### PR DESCRIPTION
**Pull request by dou-du**
fixes #19 

There is no need to add new key to control the transparency of the DOS curves. We can also the RGBA color format instead. I just change the DOS JSON files for the examples.

### CODE REVIEW

**Comment by dou-du** [comment]
Screenshot from 2022-09-13 14-25-57

**Comment by dou-du** [comment]
> Thanks @dou-du. Yes, it can but this makes it unintuitive to set the transparency. At least, we need to document that and give the user a recommendation on what to set.
> 
> BTW, can you revert the re-format of the JSON file, the changes are so large makes it hard to check the code change.

Yes, I just reformat the JSON files.

**Comment by unkcpz** [comment]
From the perspective of users, it is for sure not very convenient to set the line color and background color using to format. I insist to add the `backgroundAlpha` (optional parameters) for the background transparency and convert the alpha and color to rgba value for js script.

Feel free to have a quick meeting and have more discussions.

**Comment by unkcpz** [comment]
Convered by #33

**Pull request closed without merging**
